### ISSUE TITLE
Push notifications to users.

### ISSUE THREAD

**Issue by johnneed** [codeforbtv/green-up-app-old#10]
We need a way of alerting users when something new happens on the app.  Like a new message or a request to join the team.

iOS and Android support adding alert indicators to app icons that can be pushed to users.

We are currently using a deprecated push notification key:  here's the error message

```
You're using deprecated Apple Push Notifications certificate. Read our docs to learn how to use more modern solution. https://docs.expo.io/versions/latest/distribution/building-standalone-apps/#switch-to-push-notification-key-on-ios
```

**Comment by johnneed** [comment]
Here's a good place get started:

https://docs.expo.io/versions/latest/guides/push-notifications/

This will require a little bit of Firebase work.    

 Here's an article on sending push notifications via Firebase Cloud Messaging:   https://docs.expo.io/versions/latest/guides/using-fcm/

 
One more thing:  There are two kinds of messages,  direct and team.  a user's direct messages are in the path /messgages/<uid>    and team messages are in a path under each team. /teams/<teamID>/messages

you'll have to write a function that looks for changes under both those places, sending push notifications all team members and individuals.  The vast majority of messages are team messages.   DM's can only be created in the Green Up Admi****

**Comment by doub1ejack** [comment]
I think this would make a big difference in the user experience, but I don't know whether this should be prioritized above getting the app into the stores.  Questions:
* Can this feature be added as an "Over The Air" enhancement?
* If we add push notifications _**after**_ someone downloads the app, are we missing an important window for the user to opt-in?
