### ISSUE TITLE
Firebase error when opening a message.

### ISSUE THREAD

**Issue by mfelix5** [codeforbtv/green-up-app-old#104]
To reproduce: From the message board, tap on a message. In the console, you'll see:

Function CollectionReference.doc() requires its first argument to be of type non-empty string, but it was: undefined

This is coming from the updateMessage function.

**Comment by johnneed** [comment]
I may have already fixed this.  I found a bug in the updateMessage method.  Fixed it, but didn't test this issue.

**Comment by mfelix5** [comment]
It looks like you did fix this. I can no longer reproduce. Closing issue. Thanks!
