### ISSUE TITLE
Firestore error when accepting an invitation to a team

### ISSUE THREAD

**Issue by mfelix5** [codeforbtv/green-up-app-old#105]
To reproduce: With user A, create a team and invite user B to join. Log in as user B and accept the invitation. In the console, you'll see:

Missing or insufficient permissions.
- node_modules/@firebase/firestore/dist/index.cjs.js:352:32 in FirestoreError

I'm looking through the database for the first time now and not completely sure what things should look like. It seems that we have some partial saves happening and inconsistencies between profiles/teams and then teams/members.

**Comment by johnneed** [comment]
I'm working on invitations now.  I'll fix this while I'm in there.

**Comment by johnneed** [comment]
@mfelix5 Can you retest this?   I can't recreate this.  I think this bug was related to issue 116, which was fixed.

**Comment by mfelix5** [comment]
@johnneed , I can reproduce in current version of 'master'. To reproduce, I created a new team "Testing Monday". I invited another user. Logged in as that second user, I accepted the invitation. In the console, I see: 

"setupTeamMessageListener Error for team sLXtL8UzwS9HPPUl8LJl"
[10:01:26] Missing or insufficient permissions.
- node_modules/@firebase/firestore/dist/index.cjs.js:352:32 in FirestoreError

**Comment by johnneed** [comment]
This is not an error or bug.  The addTeamMember method in firebase-data-layer.js  tries to remove any requests to join a team.  For an invitation there might not be a request.  This results in the "permissions error" which is caught and handled.

Nothing to fix here.
