### ISSUE TITLE
Shorten App name for iOS

### ISSUE THREAD

**Issue by johnneed** [codeforbtv/green-up-app-old#12]
Change the name of the App from GreenUpVermont to Green Up VT so it fits under the icon in iOS. Currently the Name appears on an iPhone as "GreenUpVer..."

This is just reconfigure and re-submission issue to Apple.

**Comment by smara-codes** [comment]
Fixed in https://github.com/codeforbtv/green-up-app/commit/4387e0f212a0f8fd5374a8b77d185d047ebc7e30#diff-6a1b6963e828b69fcc667e3c45df78bb
