### ISSUE TITLE
Supply pickup location undefined

### ISSUE THREAD

**Issue by smara-codes** [codeforbtv/green-up-app-old#121]
1. Navigate to the Trash Tracker screen
2. Tap on one of the green pins (Supply pickup locations)
Expected Result: Pickup information is displayed in the bubble
Actual Result: _undefined, undefined_ is displayed instead

![Screenshot_20190325-202447](https://user-images.githubusercontent.com/1213709/54962758-7de06200-4f3c-11e9-9042-41c5cf37bb5e.png)

**Comment by johnneed** [comment]
Fixed
