### ISSUE TITLE
Error trying to sign in via Google. 

### ISSUE THREAD

**Issue by mfelix5** [codeforbtv/green-up-app-old#133]
**Describe the bug**
When trying to login, receive an error: 

400. That's an error.
Error: redirect_url_mismatch

**To Reproduce**
1. Download and open app via TestFlight
2. Tap on "Login with Google"
3. Tap on "Continue" at "Green Up want to use Google" prompt.

**Expected behavior**
Get logged into app.

**Smartphone (please complete the following information):**
 - Device: iPhone 6 (A1549)
 - OS: iOS v 12.1.4 (16D57)

**Comment by johnneed** [comment]
There's a bug in Expo SDK 32.
See this Stackoverflow for details: https://stackoverflow.com/questions/54333951/how-to-fix-redirect-uri-mismatch-error-while-using-expo-google-loginasync-in-r

Fixed and pushed a hotfix.
However.  this will break Google Login using the Expo App,   But it works for the stand alone app.
I have noted this in the code.
