### ISSUE TITLE
Allow Users to select VTrans road segments when selecting cleaning areas

### ISSUE THREAD

**Issue by johnneed** [codeforbtv/green-up-app-old#143]
[VT_Roads.geojson.zip](https://github.com/codeforbtv/green-up-app/files/3517826/VT_Roads.geojson.zip)
Use the VTrans Road Centerline data from the Open Data Portal : https://geodata.vermont.gov/datasets/VTrans::vt-road-centerline?geometry=-72.599%2C44.249%2C-72.538%2C44.259

- [x] Convert Shapefile to GeoJSON
- [x] Edit data to just the essential info to reduce file size.
- [ ] Add data to app
- [ ] display road segments on area selection map 
- [ ] Allow segments to be claimed by saving ids to teams, alongside the pin locations
- [ ] Mark segments as claimed from team data.
- [ ] Allow user to toggle off centerline data

**Comment by cfrank0214** [comment]
Downloaded shape file for VT Roads from geodata.vermont.gov, used ArcGIS to simplify lines, used QGIS to convert/validate geojson. Zip file attached:
[VT_Roads.geojson.zip](https://github.com/codeforbtv/green-up-app/files/3517832/VT_Roads.geojson.zip)

**Comment by cfrank0214** [comment]
After reviewing the above data I noticed it is not in WGS 84 coordinate systems I have done a coord transformation. Attached is the updated file. 
[VT_Roads_WGS84.json.zip](https://github.com/codeforbtv/green-up-app/files/3725768/VT_Roads_WGS84.json.zip)
