### ISSUE TITLE
Make Team Pins on Trash maps links to Team Screen

### ISSUE THREAD

**Issue by johnneed** [codeforbtv/green-up-app-old#148]
On Trash Tracker Map, Click an orange pin (Team Area). 

Notice the popup with Team Info.   There should be an option to navigate to the team info (double click?)
![image](https://user-images.githubusercontent.com/1043179/63019290-df13be00-be68-11e9-9552-7b35e044bfd0.png)

**Comment by kmeyersvt** [comment]
Should this though? What if it's a private team?
