### ISSUE TITLE
Circle Ci build is failing at version bump

### ISSUE THREAD

**Issue by johnneed** [codeforbtv/green-up-app-old#180]
**Describe the bug**
We get this error, when running a Circle Ci build:

![image](https://user-images.githubusercontent.com/1043179/67706407-15a0a580-f98f-11e9-9285-5ee7fd0ac4c6.png)

**To Reproduce**
1. Merge a pull request into master
2. Open the Circle Ci Website and open the current build
3. Notice that the build fails on the version bump steap

**Expected behavior**
A build completes given no errors

**Comment by johnneed** [comment]
Jon Fenner has gotten this going on the MOMM project.  He might be able to offer some insight.

**Comment by enmosys** [comment]
In .circleci/config.yml, the 'npm version' command expects the version number to be in package.json, but it's currently in app.json 

Adding the version number to package.json (and also package-lock.json) fixes the original issue, but the command still fails (in Gitpod, anyway) with "Git working directory not clean." Adding '--force' to the npm version command fixes this. Need to check if this is a Gitpod-only issue
