### ISSUE TITLE
Green Up Day Live Dashboard

### ISSUE THREAD

**Issue by johnneed** [codeforbtv/green-up-app-old#19]
Let's show live stats so folks can follow along with how many bags are dropped,   we can do this on the app and maybe have a small app on the Green Up Day website that gives live stats too.

**Comment by johnneed** [comment]
@smaraf Should we shelve this? I'm thinking we'll need to discuss integrating App data with Green Up's website.   I don't think this is going to happen in 2019.

**Comment by smara-codes** [comment]
That sounds good @johnneed - not going to happen this year most likely

**Comment by johnneed** [comment]
We have trash map and leaderboard
