### ISSUE TITLE
Countdown text doesn't fit on Android phone

### ISSUE THREAD

**Issue by enmosys** [codeforbtv/green-up-app-old#193]
On my Galaxy S6, the countdown text at the top of the app home page doesn't fit.
![2019-11-07 08 04 55](https://user-images.githubusercontent.com/6533949/69200078-0fbe6000-0b08-11ea-81a2-0ac97ff8796d.png)

**Comment by kmeyersvt** [comment]
This looks fine on my Samsung S9 v10, maybe it's resolved?

**Comment by enmosys** [comment]
How many days are you showing in the countdown? I suspect this is only an issue when the number of days is three digits.

**Comment by kmeyersvt** [comment]
53, but even then the font is smaller now.  Either way, the number of days is smaller and given our priorities, I'm going to make this low and an enhancement for the next version.
