### ISSUE TITLE
Upgrade from Expo SDK 34 to Expo SDK 36.

### ISSUE THREAD

**Issue by johnneed** [codeforbtv/green-up-app-old#207]
Many libs have been moved.   Also Redux Persist 6 will not work with Exp 36 as it no longer supports Async Storage.  Please downgrade to Redux Persist 5.10.0 until the next release of Redux Persist

**Comment by aquarashmi** [comment]
Yes, I ran into this issue mutiple times and not letting user to go to green app.

![Screenshot_20200225-200031](https://user-images.githubusercontent.com/50217668/75301788-c5850300-5809-11ea-96d9-c35971875cca.png)

**Comment by kmeyersvt** [comment]
@johnneed is this a requirement  to get the app out this month? I'd like to avoid it if we could from a workload perspective.

**Comment by aquarashmi** [comment]
@johnneed  How can we bypass this warning to continue Green up testing? Clicking on Home button and refresh button as shown in screenshot doesn't help in bringing up Green up app. Rather shows the same message. As of now, I haven't been able to successfully test the app as the above error in Expo is not letting (user) to launch green up app. My tessting device is Google Pixel 3, Android version is 10. Please let me know if you want me to open new issue with steps or this opened issue will take care of the issue I reported wth upgrade SDK.
