### ISSUE TITLE
Cancel button on Profile screen doesn't work.

### ISSUE THREAD

**Issue by justin-luoma** [codeforbtv/green-up-app-old#210]
**Describe the bug**
Cancel button on "My Profile" doesn't do anything when pressed.

**To Reproduce**
1. Login into app
2. Click on Menu tab
3. Click My Profile
4. Click Cancel button

**Expected behavior**
When the cancel button is pressed the app should go back to the Menu screen.

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 10

**Phone Emulators**
 - OS: Android
 - Version Galaxy Note 10+ 5G

**Comment by blaubleu** [comment]
Replicated on
Device: iphone 6
iOS: 13.3

**Comment by kmeyersvt** [comment]
Setting as Medium because user can click the Back arrow to leave without saving  changes.

**Comment by mpettit** [comment]
Looks like this one has been fixed. Can anyone replicate?

**Comment by kmeyersvt** [comment]
@ @mpettit it is working in my android now, do you have an iphone?

**Comment by mpettit** [comment]
nice! yup, working on iphone as far as i can tell .. will close and we can reopen if we see it happening again
