### ISSUE TITLE
hide keyboard when user is done typing

### ISSUE THREAD

**Issue by blaubleu** [codeforbtv/green-up-app-old#214]
**Is your feature request related to a problem? Please describe.**
When a touch action is complete it would be a nice enhancement to hide the keyboard

**Describe the solution you'd like**
- When a user has completed typing a password it needs to hit 'Enter' to be able to proceed to the app.
- When a user has added a description to a profile hitting 'Enter' does not close the keyboard. The only actions that can be taken are on the top menu

**Describe alternatives you've considered**
We could use a common method to hide the keyboard when the touch action ends

**Screenshot**
![login_keyboard](https://user-images.githubusercontent.com/6810575/75116378-bcdbd380-5635-11ea-968c-4af5d83f4f6d.jpg)

**Comment by kmeyersvt** [comment]
@moanableu which phone and version are you using? This  looks like another issue reported  on a Moto Android v9.

**Comment by blaubleu** [comment]
I am using an iPhone 6
