### ISSUE TITLE
Login  Screen - Android v9  - Create Login buttons are not accessible

### ISSUE THREAD

**Issue by tgerade** [codeforbtv/green-up-app-old#219]
**Describe the bug**
The Create login button appears cut off at the bottom of the screen and is inaccessible.

**To Reproduce**
1. Launch the app from EXPO 
2. See attached screen grab

**Screenshots**
<img src="https://user-images.githubusercontent.com/17165452/76260246-c23c3f00-622d-11ea-828b-a28e03f299e9.png" width=300/>

<img src="https://user-images.githubusercontent.com/1809882/78729439-08a5bc00-7908-11ea-8821-37fead4cffce.png" width=300/>

**Smartphone # 1:**
 - Device: Motorola Moto Z2
 - OS: Android version 9
 - Version 9 build PCX29.159.21-3

**Smartphone # 2:**
 - Device: iPhone 5
 - OS: iOS 12.1.4

**Comment by kmeyersvt** [comment]
@tgerade Thanks for all the details, I just tried it on my Samsung S9 and it worked fine ... can you please try again? And do you have anything set on your phone to enlarge screens or font sizes?

I'm on Android Version 10

**Comment by tgerade** [comment]
Thanks Katrina.  I just tried again, issue remains.  My font size was set to default, I tried making it small but the screen layout did not change.  I tried restarting my phone, new scan of the QR code in EXPO, but no luck.  Maybe it is just my phone.  I am very glad to hear your samsung worked.  I will see if I can update to version 10.  No, my phone says I am up to date.

**Comment by kmeyersvt** [comment]
It's good to know there's version difference to explain it.  I had
different issues with the keyboard and login screens. There are now four
tickets...

**Comment by kmeyersvt** [comment]
Moved back to In Progress because while you CAN  see the password field and buttons, you can no longer  see the username  field that you're typing in. It shouldn't  hide that until you tap into  the  password  field.

**Comment by kmeyersvt** [comment]
![Screenshot_20200326-101829_Expo](https://user-images.githubusercontent.com/37085086/77657550-d9786d80-6f4b-11ea-824d-8ed329a71e39.jpg)

**Comment by kmeyersvt** [comment]
This is also an issue on the Create Account screen.
