### ISSUE TITLE
Login button on iPhone X is hidden by the keyboard

### ISSUE THREAD

**Issue by iritush** [codeforbtv/green-up-app-old#220]
**Describe the bug**
Login button on iPhone X is hidden by the keyboard

**To Reproduce**
1. Launch the app with no user logged in
2. Start entering login details --> email and password fields visible, but login button only shows the very top part of it. The rest is covered by the keyboard.
3. Enter email and password of existing user
4. Try to tap areas outside the login fields --> keyboard does not release
5. Tap 'return' on the keyboard --> keyboard is released and login button is visible and usable
6. NOTE: if you tap the visible area of the button when the keyboard is still up and covers the rest of it, it responds and and logs in successfully.

**Expected behavior**
Login button is visible when keyboard is up

**Screenshots**
Unfortunately, when taking a screenshot, the keyboard is not detected so it doesn't appear in the screen shot. Hopefully this is easy to reproduce

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.3.1

**Comment by iritush** [comment]
This seems related to #214

**Comment by benglass** [comment]
I am not able to reproduce on an iOS emulator of iPhone X, the login button is still visible even with the keyboard open.

![image](https://user-images.githubusercontent.com/1964631/76673397-e6c05000-657a-11ea-8978-8b1674c34cc0.png)

But I can certainly reproduce it on a smaller screen device like the iphone 6

![image](https://user-images.githubusercontent.com/1964631/76673442-81209380-657b-11ea-8a92-b9e27eaad0fb.png)

I can also reproduce on either device that you can't easily close the keyboard, certainly not be simply tapping/clicking outside the inputs

**Comment by johnneed** [comment]
@moanableu @kmeyersvt  @bmoreini  @iritush  Can we test and confirm this has been fixed?   We'll needed someone with an iPhoneX or older.  I have a 10 and here's what I see.

![image](https://user-images.githubusercontent.com/1043179/77256540-61593180-6c45-11ea-9bae-307522904a86.png)

**Comment by iritush** [comment]
@johnneed Just tried this on my iPhone X. I am using local environment with master & firebase-dev.
![IMG_1E2174A21A22-1](https://user-images.githubusercontent.com/35077819/77256873-2fe16580-6c47-11ea-9595-167999ae15ab.jpeg)

**Comment by iritush** [comment]
Fixed. Tested on iPhone X with Test Flight v3.25.20
