### ISSUE TITLE
Login Screen - Android  10 - keyboard  covers the password field

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#221]
**Describe the bug**
When you  tap into the Password  field on the login screen, the keyboard covers  the  password field and you can't see what you're typing.

**To Reproduce**
1. Make sure you're logged  out of the app.
2. Enter a username, hit the Done key on the keyboard or the back arrow on your device.
3. Tap in the Password field.
4. The keyboard covers the Password field. You can type in it, but you can't see it.

**Expected behavior**
Password field should scroll up above the keyboard.

**Smartphone (please complete the following information):**
 - Device: Samsung S9
 - Version 10

**Comment by johnneed** [comment]
@kmeyersvt Can we test this again and confirm if it's fixed or not?

**Comment by iritush** [comment]
Tested on iPhone X with Test Flight v3.25.20. Doesn't reproduce

**Comment by kmeyersvt** [comment]
It doesn't cover the password field now, but now it's covering the email field.  I updated a different ticket with that info, but here's the current screen shot.

**Comment by kmeyersvt** [comment]
When I try to log in and tap in the email field,  I can't see it. 

![Screenshot_20200407-193803_Expo](https://user-images.githubusercontent.com/37085086/78729181-61288980-7907-11ea-9d3a-766208612ab8.jpg)
