### ISSUE TITLE
Clicking Record Your Trash crashes app

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#223]
Describe the bug
On the map, tap "Record Your Trash", the app reboots through the splash screen to the menu.

To Reproduce

1. Log into the app.
2. Tap the Trash icon at the bottom.
3. Tap "Record your Trash"
4. App crashes through the splash screen and returns you  to the menu.

Expected behavior
It's blue, I expected it to do something. Especially since I'm not seeing any info about the town that I'm in. I really didn't expect it to do anything, but I tried it because I couldn't drop a  pin.

Smartphone (please complete the following information):

Device: Samsung S9
Version Android v10

**Comment by nfloersch** [comment]
On iPhone Xs it does not reboot app automagically... but yes, it totes crashes the app when you hit "Record your trash"

**Comment by nfloersch** [comment]
Accidentally closed issue instead of commented on issue... duh.

**Comment by nfloersch** [comment]
![RPReplay_Final1584241105](https://user-images.githubusercontent.com/4584739/76694515-1ee29400-664a-11ea-84c6-63d03f925f3d.gif)

**Comment by kmeyersvt** [comment]
@johnneed this still crashes on my android

**Comment by johnneed** [comment]
This button has been removed.  If you're still seeing it,  try reloading the app by scanning the barcode on  this site: https://expo.io/@c4btv/Green-Up-Vermont?release-channel=qa

**Comment by johnneed** [comment]
Closing issue since the button is removed.   If there is a different issue, please submit a separate bug report.  :-)
