### ISSUE TITLE
Create Account - Keyboard covers Name Field and Create Account button

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#224]
**Describe the bug**
When you are filling  out  the Create Account screen, you can see the Email  and Password  fields, but you can't see the  Name and Create Account buttons.

**To Reproduce**

**Make sure you're logged out of the app.**
1. On login  screen.
2. Tap Create Account. 
3. Fill out Email and Password.
4. You can't see the Name field or the Create Account buttons unless you close the keyboard.

**Expected behavior**
Name field should scroll up above the keyboard if you've tapped into it.

Smartphone (please complete the following information):

Device: Samsung S9
Version 10

**Comment by iritush** [comment]
Tested on iPhone X with Test Flight v3.25.20. Doesn't reproduce

**Comment by kmeyersvt** [comment]
This screen is doing the same thing on Android as the login screen - when I tap in the email field, the keyboard pushes the email field out of view so I can see what I'm typing.

**Comment by kmeyersvt** [comment]
see #219 for screen shot
