### ISSUE TITLE
Saving New Team clears the form 

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#225]
**Describe the bug**
When you click Save on the Create a Team screen, it clears the  screen  but doesn't  close it. It does create the  team, but you think it didn't.

**To Reproduce**

1.  Click Start a Team
2. Fill out page
3. Click Save Team
4. The  page clears and if  you tap Back, the team has actually been created.

After I did this three times, it crashed when I hit Save.

**Expected behavior**
I expect the page to close after I save it and return me to the menu.

**Smartphone (please complete the following information):**
 - Device: Android Samsung  S9
-  Version 10

**Comment by benglass** [comment]
Going to try to take a peak at this over the next few days, am certainly able to reproduce on expo ios emulator

**Comment by kmeyersvt** [comment]
Passed.
