### ISSUE TITLE
Did not receive email

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#227]
I sent an invite email while logged in as kmeyersvt@gmail.com. I sent it to kmeyersvt@comcast.net.  I did not receive it. I waited 12 hours.

**Comment by kmeyersvt** [comment]
John said that we need a new template for SendGrid put into the database.

@johnneed is there a reason  we can't use last  year's and just  change  the date? Does Kate need to review/approve wording?

**Comment by johnneed** [comment]
of course we can.

**Comment by kmeyersvt** [comment]
so @johnneed  what else is preventing the emails from sending

**Comment by iritush** [comment]
@johnneed @kmeyersvt a couple of questions:
(1) It looks like the apikey for sendgrid is missing from the firebase functions environment configuration. Where can I get that key? Is it the same key as the app key, or is it different?
(2)What is the template for SendGrid mentioned above?

**Comment by doub1ejack** [comment]
Hi Irit!  Thanks for looking into this - sorry I'm just now seeing your comment.  I've shared the [Green Up project password spreadsheet](https://docs.google.com/spreadsheets/d/1ZJmFUJOCS4LAIjRc5-emwHR3JNfrO3hQd6h_sgmG3Pw/edit#gid=0) with you and created & added the api key in there. The credentials for the sendgrid account are also in there so you can pop into that account if you need anything else.

It would be great if you could add that env var to all 3 firebase environments. I just added you to the production firebase env and you were already a member of QA & Dev. Let me know how that goes.

**Comment by doub1ejack** [comment]
Hm, @iritush upon looking further through the sendgrid account, I see both [dynamic templates](https://mc.sendgrid.com/dynamic-templates) and a [design library](https://mc.sendgrid.com/design-library/your-designs). I'm not sure what either of those mean, but it sounds like perhaps we define the templates in the sendgrid account and reference them from within the code? 

@johnneed can you confirm that's how it works?

**Comment by iritush** [comment]
After updating the api key, hit this error **a couple of weeks ago**:
Billing account not configured. External network is not accessible and quotas are severely limited. Configure billing account to remove these restrictions
And seeing this error after an attempt to send the email using sendgrid:
Error: getaddrinfo EAI_AGAIN api.sendgrid.com api.sendgrid.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)

Now, the QA env seems to be missing the API Key. I am going to fix that and try again

**Comment by iritush** [comment]
Updated apikey in dev, qa and prod environments

**Comment by iritush** [comment]
It looks like the last thing that was missing was updating the template id. I created environment variables for the template id and the from email and deployed these changes (including the environment variables) to the dev environment (to test it) so this can be tested now.  PR: #322

**Comment by kmeyersvt** [comment]
Thank you all! I'll try it

**Comment by doub1ejack** [comment]
I haven't had any luck yet myself. Would you invite me and Katrina to a
team? Maybe I'm doing something different.

Thanks for all your help!

**Comment by kmeyersvt** [comment]
I haven't had luck yet either getting emails for private teams.

**Comment by iritush** [comment]
Bummer. I will take a look

**Comment by iritush** [comment]
I retested using the app on my iPhone.(3.0.12). Was able to send and receive the invite and join. Tested private group as well as public. @kmeyersvt @doub1ejack I just invited you to a private group. Can you check if you received it?

**Comment by kmeyersvt** [comment]
I just got an email from earlier this morning!

**Comment by iritush** [comment]
In the server logs, the I see the following error:
 at Request.http [as _callback] (node_modules/@sendgrid/client/src/classes/client.js:124:25)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:466:23)
    at Request.<anonymous> (node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:466:23)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)

**Comment by iritush** [comment]
The latest code was not on the QA firebase env. After re-deploying, this is now working.

**Comment by iritush** [comment]
Accidentally closed the issue. Still needs to be tested.
