### ISSUE TITLE
Map is not geolocating.

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#228]
**Describe the bug**
Last night, I was able to see and interact with the app. Today when I pull it up,  I  see the big global  map  and then  it's just a blue screen. Turns out it zoomed all  the way into the Gulf of Guinea (apparently this is called "Null Island" in geoloc speak). I have location services on, it should take me to my actual or cached location.

If you're still logged in, it sometimes geoloc's properly.  If not, you're in the Gulf  of Guinea and have to pinch zoom.

**To Reproduce**
1. Log out. Log back in as kmeyersvt@gmail.com/password
2. Tap Trash
3. See world map, then see nothing but blue.

**Expected behavior**
I expect it to geoloc to my location or use the cached location

**Smartphone (please complete the following information):**
 - Device: Samsung S9
 - Version v10

**Comment by nfloersch** [comment]
Also happens on iPhone X. Map loads to Null Island.

**Comment by kmeyersvt** [comment]
passes on Android. Moving to Done.
