### ISSUE TITLE
EXPO QA: Error message pops up when try to load app or use the app using Expo.

### ISSUE THREAD

**Issue by aquarashmi** [codeforbtv/green-up-app-old#231]
**Describe the bug**
When load Green up app using Expo app, it keeps showing the attached error message.

**To Reproduce**
1. Go to 'Expo app'.
2. Within expo app, Click on 'Geen up'
3. See error as attached.

**Expected behavior**
Green up app should load without any error message.

**Smartphone (please complete the following information):**
 - Device:  Pixel 3
 - OS: Android 
 - Version: 10

**Screenshot**
![Screenshot_20200225-200031](https://user-images.githubusercontent.com/50217668/76370661-00109480-630e-11ea-9c8f-c23bdc6baaed.png)

**Additional context**
This issue keeps happening when try to use the Green up if somehow user is able to pass this message when lauch through expo app. I believe that this error has to do with QA environment SDK version not running  as needed by expo.

**Comment by aquarashmi** [comment]
This issue is not letting me test the green up app.

**Comment by doub1ejack** [comment]
Closing. This should have been addressed by #207.
