### ISSUE TITLE
Redux-Persist Failed to Create Sync Storage

### ISSUE THREAD

**Issue by nfloersch** [codeforbtv/green-up-app-old#242]
**Describe the bug**
Error message at app launch that "redux-persist failed to create sync storage. falling back to noop storage." On phone this is a typical big-red-error screen at launch.

**To Reproduce**
1. Seems tied to a local development environment. Not sure on GitPod
2. Launch app - error appears.
3. Error can be dismissed and app will run - but without offline storage function presumably.

**Expected behavior**
Expect no error at all on launch.

**Screenshots**
I do not have a mobile screen screenshot at moment, but on local console the same error is shown.
![Screen Shot 2020-03-14 at 9 48 39 PM](https://user-images.githubusercontent.com/4584739/76694076-a88f6300-6644-11ea-9919-a391785baa1b.png)

**Smartphone (please complete the following information):**
 - iPhone Xs (Nick)
 - Google Pixel 3a (Micah)

**Additional context**
Reported by another iPhone and an Android user. Seems unrelated to device.

**Comment by doub1ejack** [comment]
For testing purposes, this error is not reproducible.  It occurs when the app starts if react native is unable to create offline storage you will see this console error:
<img src="https://user-images.githubusercontent.com/1809882/76708558-09af4900-66ce-11ea-8ec3-da592de189cc.png" width=350/>

**Comment by aquarashmi** [comment]
@nfloersch @doub1ejack  How to test this issue when this particular error was reproducible in local development environment and not in QA environment?
