### ISSUE TITLE
Tapping on a team crashes the app

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#248]
**Describe the bug**
When  you tap on a team - one created either  prior to today 3/17 or after, it crashes the app through two logo screens and  back to the main page (you're still logged in).

**To Reproduce**
1. Log in.
2. Tap on a team.
3. App crashes through  two 50th anniversary  log pages, then returns to the main  page.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a

**Additional context**
Running the app locally produces this error when clicking on a team: 
<img src="https://user-images.githubusercontent.com/1809882/77604481-fa5ba700-6ee8-11ea-85ea-ed18364b1ee5.png" width=350/>

**Comment by kmeyersvt** [comment]
This is no longer crashing the app when  I test in the current version. @doub1ejack please close if you agree on the back end.

**Comment by kmeyersvt** [comment]
Hmm, I  take it back. I tapped Mad Maxx and  it crashed. But tapping  on a team I created today doesn't crash.

**Comment by doub1ejack** [comment]
@kmeyersvt I am still seeing this error with my Pixel 3a, but on my old iPhone 5s it works fine. What version are you seeing it error out on?

**Comment by kmeyersvt** [comment]
It's intermittent on my Android v10. It's nearly always the first team that I tap after logging in. Sometimes it crashes out through the logos and back in. Sometimes it blue screens and says that something went wrong. Sometimes it opens the details.

**Comment by nfloersch** [comment]
I'm not seeing it on my iPhone XS and not in the iOS Simulator...

**Comment by nfloersch** [comment]
Reported by @kristylynn1984 as #274
