### ISSUE TITLE
About Green Up Day: remove FAQ button

### ISSUE THREAD

**Issue by doub1ejack** [codeforbtv/green-up-app-old#251]
**Is your feature request related to a problem? Please describe.**
Currently there is no FAQ data, just a heading.

**Describe the solution you'd like**
Either: 
1. remove this heading from the About screen, or 
1. get some FAQ data from Kate @ Green Up VT and display it

**Additional context**
It looks like the "Contact Us" info is present in Firestore, but the data to be displayed is not present.  

![image](https://user-images.githubusercontent.com/1809882/76720242-a267b800-6712-11ea-9651-22d9aa40a066.png)

The `screens/green-up-facts-screen` file shows that the faqs are expected to be present in the same object, but they are missing:

```
const mapStateToProps = (state: Object): Object => {
    const eventDate = state.about.date || null;
    const eventDescription = state.about.description || "";
    const faqs = state.about.faqs || [];
    const eventName = state.about.name;
    const contactUs = state.about.contactUs || {};
    return { eventDate, eventDescription, eventName, faqs, contactUs };
};
```

If we have some data we want to display it shouldn't be too hard to add it to firestore at `eventInfo > eventSettings > faq`. Then we could use the `contactUs` code as a pattern for retrieving this data.

**Comment by doub1ejack** [comment]
@kmeyersvt If you think this is something we'd like to do, it might be helpful to reach out to Teresa for content.  It might also be a good idea to only display this heading if/when there are FAQs to display.

**Comment by kmeyersvt** [comment]
Yes, I've asked Teresa. Either we get info or remove the FAQ button.

**Comment by kmeyersvt** [comment]
I think we should remove this, Teresa said we didn't have them last year.
