### ISSUE TITLE
Unable to drop trash via the "Trash Disposal" screen

### ISSUE THREAD

**Issue by iritush** [codeforbtv/green-up-app-old#255]
**Describe the bug**
Unable to drop trash via the "Trash Disposal" screen

**To Reproduce**
1. Go to "Trash Disposal" from the main menu
2. "Sorry, we have no information on trash drops for your location" message appears.
3. Can't enter bag number or move on to actually dropping trash 

**Expected behavior**
Ability to drop trash

**Screenshots**
![Simulator Screen Shot - iPhone 8 - 2020-03-17 at 16 41 14](https://user-images.githubusercontent.com/35077819/76900068-0bfcd900-686f-11ea-8602-6615438a0745.png)

**Smartphone (please complete the following information):**
-iPhone X device

**Phone Emulators**
 - OS: iOS

**Additional context**

**Comment by iritush** [comment]
Possibly related to #223

**Comment by johnneed** [comment]
fixed in another ticket
