### ISSUE TITLE
Team pages display my location - not the team's location

### ISSUE THREAD

**Issue by doub1ejack** [codeforbtv/green-up-app-old#260]
**Describe the bug**
The "Cleaning Location" map defaults to my location instead of the team location. 

**To Reproduce**
- Go to "Find a team" 
- Click on any team (Eg "Mad Maxx")
- The "Cleaning Location" map defaults to my location (Huntington) instead of the team location (presumably somewhere in Colchester)

**Expected behavior**
I expect the map to zoom in on Colchester with a red dot for the meeting location.

**Screenshots**
![image](https://user-images.githubusercontent.com/1809882/77253111-bfc6e580-6c2e-11ea-8587-a3fd1030972f.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: current
 - Browser: Chrome
 - Version: current

**Comment by blaubleu** [comment]
Also noticed a 6+ second delay when the maps is rendering. 
![map_delay](https://user-images.githubusercontent.com/6810575/77859497-d5608000-71d7-11ea-9e84-b0e52d627c33.jpg)
