### ISSUE TITLE
Can't pick a custom team start and end time

### ISSUE THREAD

**Issue by iritush** [codeforbtv/green-up-app-old#261]
**Describe the bug**
Can't pick a custom team start and end time

**To Reproduce**
1. Create a new team/Go to an existing team's details page
2. Attempt to pick a start or end time: only "Pick a starting/ending time" text appears with no options to select a time
3. Tap confirm: A default time is selected: 9am for start and 5pm for end

**Expected behavior**
Ability to select a custom time

**Screenshots**
![IMG_63C7C3154514-1](https://user-images.githubusercontent.com/35077819/77254352-ea1ca100-6c36-11ea-90ef-9e812391fd40.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.3.1

**Additional context**
Environment: QA Environment

**Comment by kmeyersvt** [comment]
@iritush is this still failing? it works on my Android.

**Comment by iritush** [comment]
This doesn't reproduce anymore on my iPhone X with Test Flight v3.25.20
