### ISSUE TITLE
"<Team Member> is not a member of the team" message appears when tapping the team manager

### ISSUE THREAD

**Issue by iritush** [codeforbtv/green-up-app-old#262]
**Describe the bug**
"<Team Member> is not a member of the team" message appears when tapping the team manager

**To Reproduce**
1. Go to Manage Your Team -->Members --> tap on team Manager's name
2. Message appears: "<Team Member> is not a member of the team"

**Expected behavior**
No message.

**Screenshots**
![IMG_6F1C19951560-1](https://user-images.githubusercontent.com/35077819/77254889-21408180-6c3a-11ea-94eb-a6e2641ef85d.jpeg)

**Smartphone (please complete the following information):**
Device: iPhone X
OS: iOS 13.3.1

**Additional context**
Used the QA environment

**Comment by johnneed** [comment]
It looks like team members are getting saved with a "Not Invited" status :-(
