### ISSUE TITLE
Add town Info to the Team Details page.

### ISSUE THREAD

**Issue by johnneed** [codeforbtv/green-up-app-old#27]
Problem: It's hard to find town info for your team.

When team owners create teams, they have an option to claim a clean up area.

When a user add a new area pin,  we should add the data for that town to the team descriptions.  

Use Smara's code for finding what town a pin is in.

If the team has multiple locations, we need info for each unique town.

**Comment by deadlion2ttip** [comment]
John,

Do you mean that the page shown below should  the display the pick up and drop off locations and rules stored in firebase for the town the clean up pin is dropped in?

Also, can you assign me to this issue? I don't seem to be able to claim it myself.

![image](https://user-images.githubusercontent.com/39771562/46213519-be04b600-c306-11e8-9eea-3df911ce301c.png)

**Comment by johnneed** [comment]
The town info can bee seen by clicking on the menu tab and then clicking the "town info" button.  If there is info for whatever town the cleanup location is in, include it verbatim on the team details screen.  Maybe just before the list of team members.

**Comment by deadlion2ttip** [comment]
got it.

**Comment by johnneed** [comment]
FYI: I'm making some changes to the Town model.  Some data names have changed and some new data points added.  There is a pull-request pending with these changes.  So the changes are coming soon.
Let me know if you have any questions.

**Comment by johnneed** [comment]
Fixed by branch issue-27
