### ISSUE TITLE
Fix status bar

### ISSUE THREAD

**Issue by johnneed** [codeforbtv/green-up-app-old#28]
Currently the status bar is being covered by the app.   
We need to account for status bar height in the layout and style the status bar so the icons can be seen better.

here's a article on the status bar : 
https://blog.expo.io/the-status-bar-manager-in-react-native-6226058ecba

**Comment by kmeyersvt** [comment]
This looks fine on my Galaxy S8.

**Comment by johnneed** [comment]
I have an iPhone.   We'll need to check the Platform and add the appropriate padding to the top of the app.

**Comment by johnneed** [comment]
This is a problem in modal screens
