### ISSUE TITLE
Tapping Log Out crashes the app

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#288]
**Describe the bug**
Tap  hamburger menu, tap  log out. Crashes through logo screens  then returns to the login screen.
Android  v10 Samsung 9

It's not graceful, but it does return you to the login screen. Also, it's now asking me if I'm sure I want to log out, so that's better.

**Comment by nfloersch** [comment]
@kmeyersvt or @doub1ejack or @anismemon or @kristylynn1984 - can someone confirm if this is still an issue? It would be a MUSTFIX if it was I think? At least based on my understanding of app store acceptance.

**Comment by kristylynn1984** [comment]
@nfloersch I just tested on Android was able to log out successfully.
