### ISSUE TITLE
Trash Map settings not clickable on Android

### ISSUE THREAD

**Issue by doub1ejack** [codeforbtv/green-up-app-old#289]
**Describe the bug**
Cannot click on the lightbox icon that brings up the settings for the trash map

**Screenshots**
<img src="https://user-images.githubusercontent.com/1809882/77713797-b4b4e200-6fad-11ea-8b3e-78609def74d6.png" width="400"/>

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Google
 - Version: 3.25.20

**Comment by nfloersch** [comment]
Closed as a newer version of this ticket was created.
