### ISSUE TITLE
Trim trailing spaces when searching for an email during login or creation 

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#291]
**Describe the bug**
The autofill on the Android for entering an email address adds a trailing space to the email address. When I then try to log in or create an account, it tells me to enter a valid email address. To the user, it looks valid unless they know to tap in the field and see the space and delete it. This is likely to deter users.

**To Reproduce**
1. On the login page in the email address field, start to type your email address.
2. The keyboard will suggest things to autofill, one of them is your email address.
3. Tap your email address to auto fill
4. Put in your password and try to log in

Also, the same happens in the Create Account screen.

**Expected behavior**
When performing the lookup, the code should trim the entry of leading and trailing spaces.

Android v10, Samsung S9

**Comment by wyzwon** [comment]
If I am not mistaken, this appears to be the same issue listed in To do #190

**Comment by kmeyersvt** [comment]
Passed
