### ISSUE TITLE
Settings not clickable on trash map on android

### ISSUE THREAD

**Issue by doub1ejack** [codeforbtv/green-up-app-old#314]
**Describe the bug**
Cannot open the trash map settings lightbox.

**Expected behavior**
Touch settings icon -> see settings overlaid over the map.

** Additional context**
I suspect it's something about the way Lightbox is being implemented - possibly regarding the use of the icon as the touchable target. But I spent a few minutes trying to troubleshoot and didn't make any particular progress, so maybe that's not the issue 🤔 

**Screenshots**
<img src="https://user-images.githubusercontent.com/1809882/78456030-81d6b200-766f-11ea-86f6-5c1c425d0e4a.png" width=350/>

**App Version (found on "Menu" screen):** v3.0.6

**Smartphone (please complete the following information):**
 - Device: Google pixel 3a

**Comment by nfloersch** [comment]
Duplicate or follow on from #289 - review that ticket for additional info.

**Comment by nfloersch** [comment]
On iPhone XS the button to open the settings is clearly "shifted" such that I can activate it by tapping the upper ~3rd of the button, but the lower majority does not work. So it appears to be some sort of alignment issue.

**Comment by kmeyersvt** [comment]
If it's quicker in order to get it into the app store, I'm OK with removing this from  the Trash map.

**Comment by kristylynn1984** [comment]
Tested today in Android and I can open the trash map settings.

However once it's open, I can only toggle the first three items. The last three, "Supply Pickups," "Collected Trash" and "Team Cleaning Areas," can't be moved. 

![Screenshot_20200412-093259_Expo](https://user-images.githubusercontent.com/62626323/79070021-bb777080-7ca0-11ea-81d6-8baaaca09285.jpg)
![Screenshot_20200412-093254_Expo](https://user-images.githubusercontent.com/62626323/79070023-bc100700-7ca0-11ea-8689-d76123bea493.jpg)
