### ISSUE TITLE
Scrolling inconsistent in Manage Teams

### ISSUE THREAD

**Issue by kristylynn1984** [codeforbtv/green-up-app-old#316]
Not able to consistently scroll up and down within the Manage Teams > "Details section. 
I was unable to scroll down until I had tapped in both the Team Name and Clean Up Site fields. 
I was able to scroll back up and down without issue as long as I didn't click on the map.
If I clicked a point on the map, the screen got stuck and I could only scroll within the map.

**To Reproduce**
1. Go to 'Manage your team'
2. Click on 'Details'
3. Try to scroll
4. See description above

**Expected behavior**
Ability to scroll up and down on the Manage Team > Details page

**Screenshots**
![Screenshot_20200405-070232_Expo](https://user-images.githubusercontent.com/62626323/78473231-0592ac00-770d-11ea-8021-714a50625700.jpg)
![Screenshot_20200405-070111_Expo](https://user-images.githubusercontent.com/62626323/78473233-06c3d900-770d-11ea-97e3-54e23e596c4a.jpg)

**App Version (found on "Menu" screen):** 3.0.8 2020-4-4

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android / Samsung Experience
 - Version 8.0.0 / 9.0

**Comment by enmosys** [comment]
#339 also?

**Comment by nfloersch** [comment]
Closing as similar issue to #339 like @enmosys noted.
