### ISSUE TITLE
Promise rejected when inviting a user to a team

### ISSUE THREAD

**Issue by aleccaputo** [codeforbtv/green-up-app-old#32]
`[19:35:49] [Unhandled promise rejection: Error: Reference.child failed: First argument was an invalid path = "invitations/john:need@gmail:com/-LMdqxoJUH895xMU1x5t". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]"]
- node_modules\@firebase\database\dist\index.cjs.js:1611:24 in validatePathString
- node_modules\@firebase\database\dist\index.cjs.js:1622:23 in validateRootPathString
- node_modules\@firebase\database\dist\index.cjs.js:13926:39 in child
- node_modules\@firebase\database\dist\index.cjs.js:15089:53 in ref
* data-sources\firebase-data-layer.js:258:11 in inviteTeamMember
* screens\teams-screen\actions.js:46:47 in <unknown>
* screens\teams-screen\actions.js:44:28 in _callee2$
- node_modules\regenerator-runtime\runtime.js:62:44 in tryCatch
- node_modules\regenerator-runtime\runtime.js:296:30 in invoke
- node_modules\regenerator-runtime\runtime.js:114:28 in <unknown>
- node_modules\regenerator-runtime\runtime.js:62:44 in tryCatch
- node_modules\regenerator-runtime\runtime.js:152:28 in invoke
- node_modules\regenerator-runtime\runtime.js:195:17 in <unknown>
- node_modules\promise\setimmediate\core.js:45:7 in tryCallTwo
- node_modules\promise\setimmediate\core.js:200:23 in doResolve
- node_modules\promise\setimmediate\core.js:66:12 in Promise
- node_modules\regenerator-runtime\runtime.js:194:27 in callInvokeWithMethodAndArg
- node_modules\regenerator-runtime\runtime.js:217:12 in enqueue
- node_modules\regenerator-runtime\runtime.js:114:28 in <unknown>
- node_modules\regenerator-runtime\runtime.js:241:8 in async
* screens\teams-screen\actions.js:43:11 in _callee2
- node_modules\redux-thunk\lib\index.js:11:24 in <unknown>
- node_modules\redux\lib\bindActionCreators.js:7:20 in <unknown>
* screens\teams-screen\invite-form.js:56:42 in _inviteToTeam
- node_modules\react-native\Libraries\Components\Touchable\TouchableHighlight.js:240:45 in touchableHandlePress
- node_modules\react-native\Libraries\Components\Touchable\Touchable.js:746:34 in _performSideEffectsForTransition
`

**Comment by aleccaputo** [comment]
Got this in my console when inviting john to join my team. 
Just tried inviting him again, now i don't get the error.

**Comment by johnneed** [comment]
fixed
