### ISSUE TITLE
'Choose Team' control in the "Send A Message" screen is hard to use

### ISSUE THREAD

**Issue by johnneed** [codeforbtv/green-up-app-old#33]
Steps to reproduce:

1) Make sure you are members of at least 2 teams.
2) Navigate to  Messages
3) Click "New Message"
4) Notice that Clicking on "Select Team to Message" does nothing.
5) To change teams you have to carefully scroll up and down inside the teams box.

Expected Behavior:
It should be obvious and easy to change teams

**Comment by tfavorite** [comment]
@johnneed is this by chance a problem on iOS only? It looks ok on my Samsung Galaxy S8...

**Comment by johnneed** [comment]
Probably is an iOS issue.  on iOS the control renders as a spinner.  which requires "scrolling" through a selection.   The real estate is small so it's a bit awkward.    We just need a better control for iOS.  I'm not sure how it looks on Android.

**Comment by kmeyersvt** [comment]
This works fine on my Android Galaxy S8.

**Comment by johnneed** [comment]
closing this, until we can decide what we want in the future.   maybe a UI redo for VNext? @smaraf
