### ISSUE TITLE
Cannot scroll in Manage your Team page

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#339]
**Describe the bug**
On  my android, I can't scroll down past the map when  in  Manage Your Team screen.  I have an S9 which has a curved screen and if I go to the very curved edge, a  very thin, faint scrollbar appears.  But on Anis' device,  he cannot scroll  past the map.

On  Thomas's Apple,  he can  get to  the bottom of the screen.

So somehow, the scrolling needs to be a wider hotspot or something  on  Android for users to be able to hit it.

S9 version 10
S7 version 8

**Comment by enmosys** [comment]
I believe I have the same problem on my S6. However, I found that if I click into an input field, I can scroll. If I click out of an input field, I can't scroll. Can anyone else confirm this behavior?

**Comment by enmosys** [comment]
Same as #316 ?

**Comment by nfloersch** [comment]
Yes @enmosys - this is similar to #316. I think the issue is the use of the React Native component "TouchableWithoutFeedback" ... I've removed that and tested briefly on iOS and Android... seems like things work better now.

**Comment by kmeyersvt** [comment]
passed testing in v5
