### ISSUE TITLE
Search for Teams by Town returns no results

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#347]
**Describe the bug**
In QA 5.0.23 - I have many public teams set up  in Colchester, but when I use the Find a Team feature and enter Colchester, it tells  me there aren't any teams.
In Prod 5.0.22 - I know there is a team in Richmond and it won't find it.

**To Reproduce**
1. Go to Find  a Team
2. Tap  the target sight icon
3. Message says "Sorry, we couldn't  find any  teams for you. Try starting your own!"
4. Or, in Find a Team, type Richmond and hit search. You get the same message.

**Expected behavior**
It should show me teams near me since my geoloc services are on and I know  there are public teams in Colchester.

It should also show me teams by town that I know are in there.

Android v10 
Samsung S9

**Comment by doub1ejack** [comment]
@kmeyersvt, is it possible this issue is related to the one @tgerade described?  Where a town won't show up if it has been marked in the admin as not having road-side pickup?

**Comment by nfloersch** [comment]
The solutions are either to search for teams by spatial intersect with town boundaries vs team "locations" ... or to fix the code that should be populating the townId into a team object... but that is not doing so.

**Comment by kmeyersvt** [comment]
it sounds like having it save the town would be easier, but I think that's compounded by the fact that the entry of the town name in a team may not be doing a lookup into the list of towns anymore. 

I have this as a 1, but maybe,  like @doub1ejack  Micah said it's not as urgent.

**Comment by doub1ejack** [comment]
I've added TownIds to 5 teams on production. Once we push this code live and verify that these 5 towns are coming up in search as expected, we can go in and do the other ~25:
- RANDOLPH
- MONTPELIER
- BURLINGTON
- SHELBURNE
- BARRE_TOWN 
- (and just now) HUNTINGTON

(... but I just discovered that maybe I don't understand how Nick's fix works, so I may need him to weigh in)
