### ISSUE TITLE
Green Up Event Info Is Display In Facts Screen

### ISSUE THREAD

**Issue by nfloersch** [codeforbtv/green-up-app-old#363]
What the admin tool shows as an event is shown in the "facts" screen.

Currently that only event shown is "Green Up Day"

But that seems the wrong place for event info.

**Comment by kmeyersvt** [comment]
@nfloersch can this be closed? I'm not sure what you were seeing, but I'm not seeing any events in the Facts screen.

![Screenshot_20200518-101215_Expo](https://user-images.githubusercontent.com/37085086/82223363-8e962900-98f0-11ea-9540-2311e092497e.jpg)
