### ISSUE TITLE
Green Up Facts Added to Admin Tool Not Shown in App

### ISSUE THREAD

**Issue by nfloersch** [codeforbtv/green-up-app-old#365]
The app's "Facts" pane does not show any facts added to that part of the database in the admin tool.

**Comment by kmeyersvt** [comment]
@anismemon  can you please check this one out too? If it's in the db properly, then it's likely similar to the town info and the app needs to be updated to pull from the new schema properly.

**Comment by anismemon** [comment]
Hi, sorry, I didn't see that you had sent me another one. Yes, the admin writes correctly to the DB.

**Comment by anismemon** [comment]
I also remember John posting about fixing that issue (on the admin side). Looks like he did it on April 29.

**Comment by kmeyersvt** [comment]
What is in QA db right now for facts? I'm seeing this this morning in 5.0.26

![Screenshot_20200518-101215_Expo](https://user-images.githubusercontent.com/37085086/82223168-5262c880-98f0-11ea-807d-04660d64cccb.jpg)

**Comment by anismemon** [comment]
@kmeyersvt The screenshot above faithfully represents the totality of what's in the Admin tool and the DB. Is that good or bad?
