### ISSUE TITLE
Town info for Free Supplies is not displaying

### ISSUE THREAD

**Issue by tgerade** [codeforbtv/green-up-app-old#367]
The map shows where to pick up the supplies, but the descriptive text regarding when, and more specifics, which is in the Admin Tool, does not appear in the app even though there is an Information box.

**To Reproduce**
1. Go to Free Supplies
2. Type in Addison
3. Notice that the Information field is blank
4. This field does have data in the admin tool

**Expected behavior**
The field should contain the data from the Admin Tool

**Screenshots**
App Screen
![image](https://user-images.githubusercontent.com/17165452/81345817-2725e100-9087-11ea-920f-c68d7d0b91cf.png)

Admin Tool Screen
![image](https://user-images.githubusercontent.com/17165452/81345580-b67ec480-9086-11ea-9ef8-f7e21433a2c6.png)

**App Version 5.0.22

**Smartphone (please complete the following information):**
 - Device: Motorola Force Z2
 - OS: Android 9
 - Browser Chrome
 - Version ?

**Phone Emulators**
 - OS:  Android
 - Version ?

**Additional context**

**Comment by kmeyersvt** [comment]
@anismemon it's unclear if it's saving data incorrectly or if it's an app issue. Could you please confirm that the Admin tool is saving data properly?

**Comment by anismemon** [comment]
@kmeyersvt Hi, as far as I can tell trash collections sites and supply distribution sites data are being saved correctly to the database through the Admin tool.

**Comment by kmeyersvt** [comment]
Thanks @anismemon.

So @nfloersch  or @doub1ejack maybe since we haven't been able to test this properly, we haven't found this spot where the schema change hasn't been updated in the app as far as where it's getting the data to display.

**Comment by tgerade** [comment]
The GPS site pins for supplies and trash are ok.  The issue is the descriptive info, like who is the town coordinator, the text about where/when you pick up supplies, the text about where/when you can drop off the trash.  You know, there will be a dump truck at the town garage to collect your trash bags on Saturday afternoon.  Stuff like that.

**Comment by tgerade** [comment]
Sorry, new user to this ...

**Comment by kmeyersvt** [comment]
No worries, I've done that too thinking I was closing the window :)

**Comment by kmeyersvt** [comment]
This passes in 5.0.26
