### ISSUE TITLE
Leaderboard not updating with total dropped bags

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#368]
**Describe the bug**
Tag bags, save them. Go to Leaderboard, it is not updated properly. If I drop 3 and then drop 10, it should show 13.  Right now it only shows the amount from the most recent drop.

**To Reproduce**
1. Go to Trash Disposal
2. Click on Bag Tagger
3. Fill out screen.
4. Tap Save.
5. Repeat process to drop additional bags.
6. Tap save.

**Expected behavior**
I expect the leaderboard to update with my team's total bags.

**Comment by kmeyersvt** [comment]
I created this based on someone else's testing.  But right now in the Expo version of the app, it tells me that it's too soon to tag bags.  @nfloersch or @doub1ejack can you please change the date in Dev so that we can test this function?

**Comment by kmeyersvt** [comment]
Anis - you  said you had this in progress I think? Assigning it to you.

**Comment by blaubleu** [comment]
When testing on an iPhone 6 we observe the following:
1. log an initial number of bags ie: 2
2. log a new number ie 7
3. in the leaderboard we still see 2 as total of bags dropped

numbers that seem to 'stick' are: 2, 5, 10
By sticking I mean they do now update on the leaderboard
