### ISSUE TITLE
Town Details entered in Admin Tool not showing in App

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#373]
The app is pulling from Comments, not Town Description. It needs to pull from Town Description.

**Comment by tgerade** [comment]
The coordinator info is stored in the admin tool under Town Description.  
The app is pulling the info from Comments.  The example I am using here is Athens.

Admin Tool screen Town Details:
![image](https://user-images.githubusercontent.com/17165452/81751459-7439f680-947d-11ea-9c84-1ac7b1f6c910.png)

App screen Trash Disposal/Town Info:
![image](https://user-images.githubusercontent.com/17165452/81751778-1a85fc00-947e-11ea-9611-3aa90c121f7c.png)

**Comment by tgerade** [comment]
I have a work around for this.  I can copy/paste the data from Town Description to comments.  Other tickets should be worked on before this one.  Namely #375,#376 & #377.
