### ISSUE TITLE
Changes made in Airplane Mode disappear when reconnecting

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#385]
**Describe the bug**

**To Reproduce**
1. Log in at least once to the app online.
2. Turn on Airplane mode
3. Drop bags on a known team.
4. Add a team
5. Turn airplane mode back off.
6. Bags should be added to your team's leaderboard
7. Your new team should still be visible.

**Expected behavior**
As long as you have loaded the app once online, any changes made in Airplane mode (teams created, bags dropped) should remain in the app and update the DB when you turn airplane mode off.

Airplane mode simulates bad cell service

**Screenshots**

**App Version (found on "Menu" screen):** [e.g. "v3.0.6"]

**Smartphone (please complete the following information):**

**Phone Emulators**
 - OS: [e.g. iOS or Android]
 - Version [e.g. iPhone 6, iPad, Google Pixel]

**Additional context**

**Comment by kristylynn1984** [comment]
Using Samsung Galaxy S7/Android version 8...

Team names do not show up. 

![Screenshot_20200518-142255_Expo](https://user-images.githubusercontent.com/62626323/82264216-7810c180-9932-11ea-9639-29dba6eb59c5.jpg)


Bag Tagger does not indicate team name. 

![Screenshot_20200518-142406_Expo](https://user-images.githubusercontent.com/62626323/82264218-7941ee80-9932-11ea-9244-562518671b9f.jpg)


Pin does not show up while in airplane mode (no image), but appears on device once airplane mode is turned off. 

![Screenshot_20200518-180549_Expo](https://user-images.githubusercontent.com/62626323/82264182-6af3d280-9932-11ea-961d-fee7934686c4.jpg)


Even though a Team Name was not indicated on the Trash Drop Screen while in airplane mode, it seems to get assigned to the team that is listed first on the home screen (if a member of more than one) once airplane mode is off.

![Screenshot_20200518-175525_Expo](https://user-images.githubusercontent.com/62626323/82264219-7941ee80-9932-11ea-93df-f0fb705c4bf0.jpg)


However the Leaderboard dpes not get updated.

![Screenshot_20200518-180601_Expo](https://user-images.githubusercontent.com/62626323/82264214-7810c180-9932-11ea-903d-6324a6260407.jpg)

**Comment by kristylynn1984** [comment]
A related issue noticed using a Samsung Galaxy S7 / Android 8 is that joining or creating a team in Airplane mood does not stick once airplane mode is turned off. Home screen reverts back to how it was before airplane mode was turned on.
