### ISSUE TITLE
Deprecated Auth method

### ISSUE THREAD

**Issue by johnneed** [codeforbtv/green-up-app-old#42]
Fix this warning:

firebase.auth.Auth.prototype.signInWithCredential is deprecated. Please use firebase.auth.Auth.prototype.signInAndRetrieveDataWithCredential instead.

**Comment by johnneed** [comment]
Hey @mfelix5 .   While you updated the method, the update caused the app to not recognize that a person has logged in.  

logging out and in again would sort of worked, but the app keeps flashing back to the login screen.

I put the deprecated method back for now. 

Can we try this again?   We'll need to make sure we fully test login before another pull request.

Thanks for all the help.   Sorry about this.

**Comment by johnneed** [comment]
FYI: This also caused the app not to recognized that permissions were granted when a user permitted it to use the location information.

**Comment by mfelix5** [comment]
ooph. I'll get on it.

**Comment by johnneed** [comment]
Thanks Mike!
