### ISSUE TITLE
Update data for 2019 Green Up Day

### ISSUE THREAD

**Issue by smara-codes** [codeforbtv/green-up-app-old#59]
To retain from 2018:
- town data
- user information

To archive:
- dropped trash pins
- teams

**Comment by johnneed** [comment]
The new schemas for the event information (dates, descriptions, faqs, etc)  have been added to the Firestore database. 
We still need to update the data-layer and initialization methods to pull this data instead of using the hard-coded data from last year.

**Comment by johnneed** [comment]
This has been fixed
