### ISSUE TITLE
Request to join a team shows 'This person is not a member...' in the message

### ISSUE THREAD

**Issue by smara-codes** [codeforbtv/green-up-app-old#60]
Steps to reproduce:

1. Log into the Green Up app to Account A
2. Create a team, 'test team A' and make sure it's public
3. Log into the Green Up app to Account B
4. Search for 'test team A' on the teams screen and ask to join
5. Log back into the app using Account A

**Expected Result:**
Should be able to see the Account B's request to join on the messages screen and should be able to accept their request 
**Actual Result:**
An error message _This person is not a member of this team_ is displayed instead.

**Comment by johnneed** [comment]
Looks like vestigial code from before the nav refactor
