### ISSUE TITLE
Invites not being sent

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#74]
1. fill out Invite Member to Team screen.
2. Tap Invite to Team
3. It clears the screen with no confirmation that the invitation was sent, and it actually wasn't. I didn't receive the invite.

**Comment by kmeyersvt** [comment]
![Screenshot_20190309-085313_Expo](https://user-images.githubusercontent.com/37085086/54072479-4fc70680-4249-11e9-866f-274643b07a5a.jpg)

**Comment by johnneed** [comment]
We need to update all functions to  work with the new firestore database

**Comment by kmeyersvt** [comment]
I just received two email invites for Team Foo.

**Comment by johnneed** [comment]
Team Foo is the bestest GU team ever!  You should definitely join.

**Comment by kmeyersvt** [comment]
Um, no Pandas Rock is the best!

**Comment by johnneed** [comment]
Updated SendGrid and Firestore Functions
