### ISSUE TITLE
Cannot drop trash bag in Williston

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#78]
The message says that leaving trash bags on the roadside is allowed, but when I tap on the screen, it doesn't mark it.

**Comment by smara-codes** [comment]
@kmeyersvt I was able to drop a trash bag in Winooski - would you mind trying this again? Also just making sure that you were tapping on the 'Drop A Trash Bag Here' button on the screen to mark it (reminder that the app uses your location to determine where to drop it and the user cannot choose the location on the map). While I was investigating this I found that the Collect functionality is broken so I'll be working on fixing that.

**Comment by tgerade** [comment]
Hi @smaraf ,
I was able to drop trash in Newport.
Teresa
