### ISSUE TITLE
Accepting an invite doesn't put me on the team

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#82]
John sent me an invite to Team Foo.
I clicked on the Message which opened the screen to accept an invite.
Tapped Accept Invite.
Bombed me to a white screen, then the loading screen, then back into Messages.
On my list of teams, there's still a ? next to Team Foo in my list and when I tap it, it brings me to the Accept Invite team. This looks like it didn't actually process me accepting the invite.

**Comment by johnneed** [comment]
Taking this one because we really need @kmeyersvt  on Team Foo.

**Comment by kmeyersvt** [comment]
Awwww, shucks.

**Comment by johnneed** [comment]
Fixed
