### ISSUE TITLE
Notification bar icons are really big

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/green-up-app-old#84]
On my notifications on my Samsung Galaxy S8, when I have Expo running the Green Up app, it's huge with huge icons. Is this Expo or is this a Green Up issue?

![Notification bar with large icons](https://user-images.githubusercontent.com/37085086/54090710-74a4a200-434d-11e9-8b62-cd397b82a7d7.jpg)

**Comment by johnneed** [comment]
Perhaps we should shorten the app name to "Green Up" in the App.json.  That would allow all Icons to fit.  
We'll also need to shorten it so the name will fit under the icon on the iphone.

**Comment by johnneed** [comment]
In Code review
