### ISSUE TITLE
Selectable Date Range for team meeting day is not correct.

### ISSUE THREAD

**Issue by bentito** [codeforbtv/green-up-app-old#91]
Steps to reproduce:
in the March 18,2019 release Android app add a new team; choose date. (see screen shot).
Expected outcome: you can choose May 15, 2019 for your date for your new team to meet.
Actual outcome: you cannot choose May 15. It is greyed out.

![image](https://user-images.githubusercontent.com/4449199/54564598-8c5dd500-49a2-11e9-9735-375a9c1bae7a.png)

**Comment by johnneed** [comment]
We only  allow you choose dates 1 week before or after Green Up day.   that actual bug is  that the selectedable range is off a little,  probably because it's still working off last year's Green Up Date.

**Comment by johnneed** [comment]
@mfelix5 is this done?  I think you've already submitted a PR for this.

**Comment by mfelix5** [comment]
@johnneed , I did submit a PR and it was merged into master. It looks to be working fine. However, @smaraf suggested we revisit the approach. I will look into this when I'm back on Green Up. Likely tomorrow afternoon.

**Comment by mfelix5** [comment]
fix merged in PRs 108 and 110.
